name: API tests
on: [pull_request, push]
jobs:
  karate-run:
    name: karate run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm install
        run: cd API && npm install  
      - name: start API  
        run: cd API npm run start
      - name: wait for api  
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:3001/'
          responseCode: 200
          timeout: 60000
          interval: 1000
      - name: debug
        run: ls
      - name: debug 2
        run: cd API/test && ls
      - name: run tests
        run: cd API && npm run test

      
